apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: halo-plugin-watermark
spec:
  enabled: true
  requires: ">=2.20.0"
  author:
    name: Manssizz
    website: https://www.isiotak.com
  logo: logo.png
  settingName: watermark-settings
  configMapName: watermark-configMap
  homepage: https://github.com/manssizz/halo-plugin-watermark
  repo: https://github.com/manssizz/halo-plugin-watermark
  issues: https://github.com/manssizz/halo-plugin-watermark/issues
  displayName: "Image Watermark & WebP"
  description: "Automatically adds watermarks and converts images to WebP format upon uploading attachments."
  license:
    - name: "GPL-3.0"
      url: "https://github.com/manssizz/halo-plugin-watermark/blob/main/LICENSE"